import AuthRequest from "../commands/authRequest";


describe('Create require', () => {
    AuthRequest();

    it('create req spec ', function () {
        cy.visit("/hire-requests")
        cy.get("button").contains("+ Добавить заявку")
            .click()
        cy.get("div[data-testid=modal-editHireRequest]")
            .find("#RequestType")
            .type(`Специалисты{enter}`)
        cy.get("#Position")
            .type(`Агент{enter}`)
        cy.get("div[data-testid=modal-editHireRequest]")
            .find("div[id='ExtraData.UserGroup']")
            .type(`Тестовая группа 2{enter}`)
        cy.get("div[data-testid=modal-editHireRequest]")
            .find("input[id='ExtraData.StaffUnitId']")
            .type(`1223344`)
        cy.get("div[id='ExtraData.LegalEntity'")
            .type(`ОАО РЖД{enter}`)
        cy.get("div[data-testid=modal-editHireRequest]")
            .find("div[id='ExtraData.OrgStructure']")
            .type(`Холдинг РЖД{enter}`)
        cy.get("div[id='ExtraData.SeniorPosition'")
            .type(`Агент{enter}`)
        cy.get("div[data-testid=modal-editHireRequest]")
            .find("div[id='ExtraData.StaffUnit']")
            .type(`Да{enter}`)
        cy.get("#Reason")
            .type(`Новая штатная{enter}`)
        cy.get("#CloseDate")
            .click()
            .get("button").contains((new Date()).getDate())
            .click()
        cy.get("div[id='ExtraData.Responsibilities']")
            .type("Функциональные обязаности текст{enter}")
        cy.get("div[id='ExtraData.Education']")
            .type("Среднее{enter}")
        cy.get("div[id='ExtraData.Expirience']")
            .type(`6{enter}`)
        //зп от
        cy.get("#Salary")
            .find("input")
            .eq(0)
            .type(15000)
        //зп до
        cy.get("#Salary")
            .find("input")
            .eq(1)
            .type(0)
        cy.get("input[id='ExtraData.MonthPremium']")
            .type(1000)
        cy.get("input[id='ExtraData.QuarterPremium']")
            .type(10000)
        cy.get("input[id='ExtraData.AnnualPremium']")
            .type(10000)
        cy.get("div[id='ExtraData.Schedule']")
            .type("Полный день{enter}")
        cy.get("input[id='Address']")
            .type("Россия, г Вологда, ул Ленина, д 10")
            .get("div")
            .contains("Россия, г Вологда, ул Ленина, д 10")
            .click()
        cy.get("input[id='ExtraData.BusinessTrips']")
            .type("Нет")
        cy.get("div[id='ExtraData.SocialBenefits']")
            .type("Базовый соц пакет")
        cy.get("textarea[id='ExtraData.ExtraBenefits']")
            .type("Доп.льготы")
        cy.get("input[id='ExtraData.Interviewer']")
            .type("Степан")
        cy.get("div[data-testid=modal-editHireRequest]")
            .find("#Responsible")
            .type("Тест Рекрутер{enter}")
        cy.get("button").contains("Сохранить")
            .click()
    });
})